### ISSUE TITLE
[suggestion] Use https://travis-ci.org/ to build releases

### ISSUE THREAD

**Issue by okurz** [IsaacSchemm/netbootcd#2]
https://travis-ci.org/ is easily integrated with github. I guess that adding the call to build.sh as well as specifying the build requirements should make it work to build releases with travis CI. I did not try to build netbootcd with travis CI myself, though.

**Comment by IsaacSchemm** [comment]
Looks like travis-ci is building it now (I made a branch so it doesn't try to build all my commits - right now, every time it builds it redownloads CorePlus ISO.)

What could I use as a place to upload the built files to?

**Comment by okurz** [comment]
> What could I use as a place to upload the built files to?

You can attach it to "releases" just here in github. This can also be automated.

**Comment by okurz** [comment]
seems you have it fixed with https://github.com/IsaacSchemm/netbootcd/releases/tag/v7.0beta3 awesome :-) If you like you can add the ribbon to the README.
